#!/usr/bin/env python

import os
import onshape_to_robot.onshape_api as api

cacheDir = os.path.dirname(api.__file__)+'/cache/'
print("Cleaning cache directory ("+cacheDir+")")
os.system("rm -rf "+cacheDir+"/*")